// Ambient env var declarations. `worker-configuration.d.ts` is generated by
// `wrangler types` from wrangler.jsonc bindings/vars and doesn't know about
// these — they're secrets, set with `wrangler secret put <NAME>` (never
// declared in wrangler.jsonc `vars`, never committed). See
// .dev.vars.example for local dev and README.md "Self-host quickstart" for
// production setup.
//
// This file has no imports/exports, so it's an ambient global script, and
// this `interface Env` merges into the global `Env` interface that
// worker-configuration.d.ts declares (TypeScript interface merging).
interface Env {
  /** Google OAuth 2.0 client ID. Checked against the ID token's `aud`
   *  claim in src/worker/auth/google.ts. */
  GOOGLE_CLIENT_ID: string;
  /** Google OAuth 2.0 client secret. Reserved for future use — the current
   *  ID-token verification flow (tokeninfo endpoint) doesn't need it. */
  GOOGLE_CLIENT_SECRET: string;
  /** Random string used to HMAC-sign the session cookie (Web Crypto
   *  SubtleCrypto) in src/worker/auth/session.ts. */
  SESSION_SECRET: string;
  /** Optional comma-separated allowlist of emails permitted to sign in.
   *  Unset = any Google-verified email is trusted. See
   *  src/worker/auth/google.ts. */
  ALLOWED_EMAILS?: string;
}
